name: Update Submodule and Run Executable

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1,4'

jobs:
  update-submodule-and-file:
    runs-on: windows-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Update Git Submodule
      - name: Update Git Submodule
        run: |
          git submodule update --init --recursive pcsx2_patches
          git submodule update --recursive --remote pcsx2_patches

      # Step 3: Run Update List Executable
      - name: Run Update List Executable
        run: |
          .\Update_list.exe

      # Step 4: Commit and Push Changes
      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Auto list update by workflow"
