name: Update Submodule and Run Executable

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 UTC every Sunday

jobs:
  update-submodule-and-file:
    runs-on: windows-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # Step 3: Update Git Submodule
      - name: Update Git Submodule
        run: |
          git submodule update --init --recursive pcsx2_patches

      # Step 4: Run Update List Executable
      - name: Run Update List Executable
        run: |
          ".\Update list.exe"

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "KrystianLesniak@users.noreply.github.com"
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
