name: Update Submodule and Run Executable

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Run at 00:00 UTC every Sunday

jobs:
  update-submodule-and-file:
    runs-on: windows-latest

    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Git
      - name: Set up Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      # Step 3: Update Git Submodule
      - name: Update Git Submodule
        run: |
          git submodule update --init --recursive pcsx2_patches

      # Step 4: Run Update List Executable
      - name: Run Update List Executable
        run: |
          .\Update list.exe

      # Step 5: Commit and Push Changes
      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Update submodule and file"
          git push
